### ISSUE TITLE
About the training of AutoEncoderKL for my diffusion model

### ISSUE THREAD

**Issue by TUAT-Novice** [masadcv/MONAI-Diffusion#1]
Hi, @masadcv. Thank you so much for your code. Recently I want to train a autoencoderkl model for latent diffusion model for my own medical images, but I have not ideas for the AE training. If possible, I would like to ask if your code can train a good 2D AE model on your dataset?

**Comment by masadcv** [comment]
Check this:
https://github.com/masadcv/MONAI-Diffusion/blob/master/2d_autoencoderkl.py
